baseURL = 'https://tmichaelan.github.io/'
languageCode = 'en-us'
title = 'Mikhail Tarchyla'
theme = "hugo-paper"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv.html"
    weight = 10